src/main/java/domain/ProjectIdeaEntity.java
package domain;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import config.User;
import enums.Extent;
import enums.State;

@Entity
@Table(name = "project_idea")
public class ProjectIdeaEntity implements Serializable {

        private static final long serialVersionUID = -4822777598934371824L;

        public ProjectIdeaEntity() {
                // JPA
        }

        public ProjectIdeaEntity(User creator, DepartmentEntity department, LocationEntity location) {
                this.creator = creator;
                this.department = department;
                this.location = location;
        }

        @Id
        private Integer id;

        private String name;

        @Column(name = "workflow_state")
        private Integer workflowState;

        @ManyToOne
        @JoinColumn(name = "creator")
        private User creator;

        private Date createdate;

        @Column(name = "current_situation")
        private String currentSituation;

        private String objective;

        private String benefit;

        @ManyToOne
        @JoinColumn(name = "cost_unit")
        private DepartmentEntity department;

        @ManyToOne
        @JoinColumn(name = "location")
        private LocationEntity location;

        private Integer extent;

        public Integer getId() {
                return id;
        }

        public void setId(Integer id) {
                this.id = id;
        }

        public String getName() {
                return name;
        }

        public void setName(String name) {
                this.name = name;
        }

        public Integer getWorkflowState() {
                return workflowState;
        }

        public void setWorkflowState(Integer workflowState) {
                this.workflowState = workflowState;
        }

        public State getWorkFlowStateAsEnum(Integer workFlowState) {
                return State.getStateByValue(workFlowState);
        }

        public User getCreator() {
                return creator;
        }

        public void setCreator(User creator) {
                this.creator = creator;
        }

        public Date getCreatedate() {
                return createdate;
        }

        public void setCreatedate(Date createdate) {
                this.createdate = createdate;
        }

        public String getCreateDateAsString() {
                String dateString = null;
                if (createdate != null) {
                        DateFormat formatter = new SimpleDateFormat("dd.MM.yyyy");
                        dateString = formatter.format(createdate);
                }
                return dateString;
        }

        public String getCurrentSituation() {
                return currentSituation;
        }

        public void setCurrentSituation(String currentSituation) {
                this.currentSituation = currentSituation;
        }

        public String getObjective() {
                return objective;
        }

        public void setObjective(String objective) {
                this.objective = objective;
        }

        public String getBenefit() {
                return benefit;
        }

        public void setBenefit(String benefit) {
                this.benefit = benefit;
        }

        public DepartmentEntity getDepartment() {
                return department;
        }

        public void setDepartment(DepartmentEntity department) {
                this.department = department;
        }

        public LocationEntity getLocation() {
                return location;
        }

        public void setLocation(LocationEntity location) {
                this.location = location;
        }

        public Integer getExtent() {
                return extent;
        }

        public void setExtent(Integer extent) {
                this.extent = extent;
        }

        public Extent getExtentAsEnum(Integer extent) {
                return Extent.getExtentByValue(extent);
        }

        @Override
        public int hashCode() {
                final int prime = 31;
                int result = 1;
                result = prime * result + ((benefit == null) ? 0 : benefit.hashCode());
                result = prime * result + ((createdate == null) ? 0 : createdate.hashCode());
                result = prime * result + ((creator == null) ? 0 : creator.hashCode());
                result = prime * result + ((currentSituation == null) ? 0 : currentSituation.hashCode());
                result = prime * result + ((department == null) ? 0 : department.hashCode());
                result = prime * result + ((extent == null) ? 0 : extent.hashCode());
                result = prime * result + ((id == null) ? 0 : id.hashCode());
                result = prime * result + ((location == null) ? 0 : location.hashCode());
                result = prime * result + ((name == null) ? 0 : name.hashCode());
                result = prime * result + ((objective == null) ? 0 : objective.hashCode());
                result = prime * result + ((workflowState == null) ? 0 : workflowState.hashCode());
                return result;
        }

        @Override
        public boolean equals(Object obj) {
                if (this == obj)
                        return true;
                if (obj == null)
                        return false;
                if (getClass() != obj.getClass())
                        return false;
                ProjectIdeaEntity other = (ProjectIdeaEntity) obj;
                if (benefit == null) {
                        if (other.benefit != null)
                                return false;
                } else if (!benefit.equals(other.benefit))
                        return false;
                if (createdate == null) {
                        if (other.createdate != null)
                                return false;
                } else if (!createdate.equals(other.createdate))
                        return false;
                if (creator == null) {
                        if (other.creator != null)
                                return false;
                } else if (!creator.equals(other.creator))
                        return false;
                if (currentSituation == null) {
                        if (other.currentSituation != null)
                                return false;
                } else if (!currentSituation.equals(other.currentSituation))
                        return false;
                if (department == null) {
                        if (other.department != null)
                                return false;
                } else if (!department.equals(other.department))
                        return false;
                if (extent == null) {
                        if (other.extent != null)
                                return false;
                } else if (!extent.equals(other.extent))
                        return false;
                if (id == null) {
                        if (other.id != null)
                                return false;
                } else if (!id.equals(other.id))
                        return false;
                if (location == null) {
                        if (other.location != null)
                                return false;
                } else if (!location.equals(other.location))
                        return false;
                if (name == null) {
                        if (other.name != null)
                                return false;
                } else if (!name.equals(other.name))
                        return false;
                if (objective == null) {
                        if (other.objective != null)
                                return false;
                } else if (!objective.equals(other.objective))
                        return false;
                if (workflowState == null) {
                        if (other.workflowState != null)
                                return false;
                } else if (!workflowState.equals(other.workflowState))
                        return false;
                return true;
        }

        @Override
        public String toString() {
                return "ProjectIdeaEntity [id=" + id + ", name=" + name + ", workflowState=" + workflowState + ", creator=" + creator
                                + ", createdate=" + createdate + ", currentSituation=" + currentSituation + ", objective=" + objective
                                + ", benefit=" + benefit + ", department=" + department + ", location=" + location + ", extent=" + extent
                                + "]";
        }

}

WebContent/secure/change-project-idea.xhtml
<ui:composition template="/template/design.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="metadata">
	</ui:define>
	<ui:define name="content">
		<h:form>
			<p:breadCrumb styleClass="ui-state-default">
				<p:menuitem value="Mein Dashboard" outcome="/secure/home.xhtml" />
				<p:menuitem value="Projektidee-Übersicht"
					outcome="/secure/projectidea-overview.xhtml" />
			</p:breadCrumb>
			<div>
				<p:tabView activeIndex="#{editProjectIdeaPresenter.activeTabIndex}">

					<p:messages id="msgs" />
					<p:growl id="growlEditIdea" for="growlEditIdea"
					showDetail="true" sticky="true" />

					<p:tab title="Übersicht">
						<p:panel id="panelOverview"
							header="Projektantrag (#{editProjectIdeaPresenter.editableProjectIdea.id}): #{editProjectIdeaPresenter.editableProjectIdea.name}">
							<p:accordionPanel multiple="true">
								<p:tab title="Ausgangssituation">
									<h:outputText
										value="#{editProjectIdeaPresenter.editableProjectIdea.currentSituation}" />
								</p:tab>
								<p:tab title="Zielsetzung">
									<h:outputText
										value="#{editProjectIdeaPresenter.editableProjectIdea.objective}" />
								</p:tab>
								<p:tab title="Nutzen">
									<h:outputText
										value="#{editProjectIdeaPresenter.editableProjectIdea.benefit}" />
								</p:tab>
							</p:accordionPanel>

							<p:panelGrid columns="2" style="width:100%"
								styleClass="borderless-grid">

								<p:outputLabel for="creatorOverview" value="Ersteller:"
									styleClass="bold" />
								<h:outputText id="creatorOverview"
									value="#{editProjectIdeaPresenter.editableProjectIdea.creator.firstname} #{editProjectIdeaPresenter.editableProjectIdea.creator.lastname}" />

								<p:outputLabel for="createdateOverview" value="Erstelldatum:"
									styleClass="bold" />
								<h:outputText id="createdateOverview"
									value="#{editProjectIdeaPresenter.editableProjectIdea.createdate}">
									<f:convertDateTime pattern="dd.MM.yyyy" />
								</h:outputText>

								<p:outputLabel for="departmentOverview" value="Kostenstelle:"
									styleClass="bold" />
								<h:outputText id="departmentOverview"
									value="#{editProjectIdeaPresenter.editableProjectIdea.department.fullname}" />

								<p:outputLabel for="locationOverview" value="Standort:"
									styleClass="bold" />
								<h:outputText id="locationOverview"
									value="#{editProjectIdeaPresenter.editableProjectIdea.location.city}" />

								<p:outputLabel for="extentOverview" value="Projektausmaß:"
									styleClass="bold" />
								<h:outputText id="extentOverview"
									value="#{editProjectIdeaPresenter.extent[editProjectIdeaPresenter.editableProjectIdea.extent]}" />

							</p:panelGrid>
						</p:panel>
					</p:tab>

					<p:tab title="Editieren"
						rendered="#{loginBean.user.userId.equals(editProjectIdeaPresenter.editableProjectIdea.creator.userId)}">
						<p:panel id="panel"
							header="Projektidee #{editProjectIdeaPresenter.editableProjectIdea.name} bearbeiten">
							<p:messages id="msgsEdit" />
							<h:panelGrid columns="2" cellpadding="5">
								<p:outputLabel for="ideaName" value="Projektidee:" />
								<p:inputText id="ideaName" styleClass="inputFields"
									value="#{editProjectIdeaPresenter.editableProjectIdea.name}"
									required="true">
									<f:validateLength minimum="5" />
								</p:inputText>

								<p:outputLabel for="currentSituation" value="Ausgangssituation:" />
								<p:inputTextarea id="currentSituation"
									value="#{editProjectIdeaPresenter.editableProjectIdea.currentSituation}"
									required="true" rows="10" cols="100" />

								<p:outputLabel for="objective" value="Zielsetzung:" />
								<p:inputTextarea id="objective"
									value="#{editProjectIdeaPresenter.editableProjectIdea.objective}"
									required="true" rows="10" cols="100" />

								<p:outputLabel for="benefit" value="Nutzen:" />
								<p:inputTextarea id="benefit"
									value="#{editProjectIdeaPresenter.editableProjectIdea.benefit}"
									required="true" rows="10" cols="100" />

								<p:outputLabel for="location" value="Standort:" />
								<p:selectOneMenu id="location" styleClass="inputFields"
									value="#{editProjectIdeaPresenter.editableProjectIdea.location}"
									converter="locationConverter" required="true">
									<f:selectItem itemLabel="Standort auswählen"
										itemValue="#{null}" noSelectionOption="true" />
									<f:selectItems value="#{editProjectIdeaPresenter.locationList}"
										var="location" itemValue="#{location}"
										itemLabel="#{location.city}" />
								</p:selectOneMenu>

								<p:outputLabel for="costUnit" value="Kostenstelle:" />
								<p:selectOneMenu id="costUnit" styleClass="inputFields"
									value="#{editProjectIdeaPresenter.editableProjectIdea.department}"
									converter="departmentConverter" required="true">
									<f:selectItem itemLabel="Kostenstelle auswählen"
										itemValue="#{null}" noSelectionOption="true" />
									<f:selectItems value="#{editProjectIdeaPresenter.costUnitList}"
										var="costUnit" itemValue="#{costUnit}"
										itemLabel="#{costUnit.fullname}" />
								</p:selectOneMenu>

								<p:outputLabel for="extent" value="Projektausmaß:" />
								<p:selectOneMenu id="extent" styleClass="inputFields"
									value="#{editProjectIdeaPresenter.editableProjectIdea.extent}"
									required="true">
									<f:selectItem itemLabel="Projektausmaß auswählen"
										itemValue="#{null}" noSelectionOption="true" />
									<f:selectItems value="#{editProjectIdeaPresenter.extent}"
										var="extent" itemLabel="#{extent.name()}"
										itemValue="#{extent.value}" />
								</p:selectOneMenu>

							</h:panelGrid>

							<p:commandButton value="Änderungen speichern" update="panel"
								actionListener="#{editProjectIdeaPresenter.updateIdea}"
								icon="ui-icon-check">
								<f:ajax onerror="window.scrollTo(0, 0);" />
							</p:commandButton>
							<p:button value="Abbrechen" outcome="projectidea-overview" />
						</p:panel>
					</p:tab>
				</p:tabView>
			</div>
		</h:form>
	</ui:define>

</ui:composition>

WebContent/secure/create-idea.xhtml
<ui:composition template="/template/design.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="metadata">
	</ui:define>
	<ui:define name="content">
		<h:form>
			<p:breadCrumb styleClass="ui-state-default">
				<p:menuitem value="Mein Dashboard" outcome="/secure/home.xhtml" />
				<p:menuitem value="Projektidee einreichen" outcome="create-idea" />
			</p:breadCrumb>
			<p:panel id="panel" header="Neue Projektidee">
				<p:messages id="msgs" />
				<p:growl id="growlCreateIdea" for="growlCreateIdea"
					showDetail="true" sticky="true" />
				<h:panelGrid columns="2" cellpadding="5">
					<p:outputLabel for="ideaName" value="Projektidee:" />
					<p:inputText id="ideaName" styleClass="inputFields"
						value="#{createIdeaPresenter.projectIdea.name}" required="true">
						<f:validateLength minimum="5" />
					</p:inputText>

					<p:outputLabel for="currentSituation" value="Ausgangssituation:" />
					<p:inputTextarea id="currentSituation"
						value="#{createIdeaPresenter.projectIdea.currentSituation}"
						required="true" rows="10" cols="100" />

					<p:outputLabel for="objective" value="Zielsetzung:" />
					<p:inputTextarea id="objective"
						value="#{createIdeaPresenter.projectIdea.objective}"
						required="true" rows="10" cols="100" />

					<p:outputLabel for="benefit" value="Nutzen:" />
					<p:inputTextarea id="benefit"
						value="#{createIdeaPresenter.projectIdea.benefit}" required="true"
						rows="10" cols="100" />

					<p:outputLabel for="location" value="Standort:" />
					<p:selectOneMenu id="location" styleClass="inputFields"
						value="#{createIdeaPresenter.projectIdea.location}"
						converter="locationConverter" required="true">
						<f:selectItem itemLabel="Standort auswählen" itemValue="#{null}"
							noSelectionOption="true" />
						<f:selectItems value="#{createIdeaPresenter.locationList}"
							var="location" itemValue="#{location}"
							itemLabel="#{location.city}" />
					</p:selectOneMenu>

					<p:outputLabel for="costUnit" value="Kostenstelle:" />
					<p:selectOneMenu id="costUnit" styleClass="inputFields"
						value="#{createIdeaPresenter.projectIdea.department}"
						converter="departmentConverter" required="true">
						<f:selectItem itemLabel="Kostenstelle auswählen"
							itemValue="#{null}" noSelectionOption="true" />
						<f:selectItems value="#{createIdeaPresenter.costUnitList}"
							var="costUnit" itemValue="#{costUnit}"
							itemLabel="#{costUnit.fullname}" />
					</p:selectOneMenu>

					<p:outputLabel for="extent" value="Projektausmaß:" />
					<p:selectOneMenu id="extent" styleClass="inputFields"
						value="#{createIdeaPresenter.projectIdea.extent}" required="true">
						<f:selectItem itemLabel="Projektausmaß auswählen"
							itemValue="#{null}" noSelectionOption="true" required="true" />
						<f:selectItems value="#{createIdeaPresenter.extentValues}"
							var="extent" itemLabel="#{extent.name()}"
							itemValue="#{extent.value}" />
					</p:selectOneMenu>

				</h:panelGrid>

				<p:commandButton value="Idee einreichen" update="panel"
					actionListener="#{createIdeaPresenter.saveIdea}"
					icon="ui-icon-check">
					<f:ajax onerror="window.scrollTo(0, 0);" />
				</p:commandButton>
				<p:button value="Abbrechen" outcome="home" />
			</p:panel>
		</h:form>
	</ui:define>

</ui:composition>

WebContent/secure/projectidea-overview.xhtml
<ui:composition template="/template/design.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">

	<ui:define name="metadata">
	</ui:define>
	<ui:define name="content">
		<h:form id="form">
			<p:breadCrumb styleClass="ui-state-default">
				<p:menuitem value="Mein Dashboard" outcome="/secure/home.xhtml" />
				<p:menuitem value="Projektidee Übersicht" outcome="projectidea-overview" />
			</p:breadCrumb>
			<p:dataTable id="projectIdeas" var="projectIdea"
				value="#{projectIdeaOverviewPresenter.projectIdeas}"
				sortMode="multiple" resizableColumns="true" scrollable="true"
				tableStyle="width:auto table-layout:fixed" 
				widgetVar="projectIdeasTable" selectionMode="single"
				selection="#{projectIdeaOverviewPresenter.selectedProjectIdea}"
				rowKey="#{projectIdea.id}" paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown} {Exporters}"
				emptyMessage="Keine Projektidee zu gegebenen Kriterien gefunden."
				reflow="true" rows="10" rowsPerPageTemplate="10,50,100" paginator="true">
<f:facet name="{Exporters}">
		
            <h:commandLink>
                <p:graphicImage name="images/pdf.png" width="24"/>
                <p:dataExporter type="pdf" target="projectIdeas" fileName="ideas" encoding="cp1252"  preProcessor="#{exporter.preProcessPDF}"/>
            </h:commandLink>
</f:facet>
				<f:facet name="header" >
				<h:panelGroup layout="block" id="tblHeader">
					<p:button id="details" icon="ui-icon-search"
						style="width:35px;height:30px;float:left"
						outcome="change-project-idea"
						disabled="#{projectIdeaOverviewPresenter.disabled}">
						<f:param name="id"
							value="#{projectIdeaOverviewPresenter.selectedProjectIdea.id}" />
					</p:button>
					<p:tooltip id="toolTipDetails" for="details" value="Detailansicht"
						position="top" />

					<p:button id="change" icon="ui-icon-pencil"
						style="width:35px;height:30px;float:left"
						outcome="change-project-idea"
						rendered="#{loginBean.user.userId.equals(projectIdeaOverviewPresenter.selectedProjectIdea.creator.userId)}"
						disabled="#{projectIdeaOverviewPresenter.disabled}">
						<f:param name="id"
							value="#{projectIdeaOverviewPresenter.selectedProjectIdea.id}" />
						<f:param name="action" value="edit" />
					</p:button>
					<p:tooltip id="toolTipChange" for="change" value="Bearbeiten"
						position="top" />

					<p:button id="changeintoProject" icon="ui-icon-check"
						style="width:35px;height:30px;float:left"
						rendered="#{!loginBean.user.role.name().equals('EMPLOYEE')}"
						disabled="#{projectIdeaOverviewPresenter.disabled}"
						outcome="admin/create-project">
						<f:param name="id"
							value="#{projectIdeaOverviewPresenter.selectedProjectIdea.id}" />
					</p:button>
					<p:tooltip id="toolTipApprove" for="changeintoProject"
						value="In Projektantrag umwandeln" position="top" />

					<p:commandButton id="infoBox" icon="ui-icon-notice"
						style="width:35px;height:30px;float:left" type="button"
						onclick="PF('dlg1').show();" />
					<p:tooltip id="toolTipInfoBox" for="infoBox" value="InfoBox"
						position="top" />

					<p:dialog header="Info" widgetVar="dlg1" modal="true" height="100">
						<h:outputText
							value="Zum Anzeigen der Projekte klicken Sie bitte auf das gewünschte Projekt." />
					</p:dialog>
						
	        		Übersicht Projektidee
	        		<p:commandButton id="toggler" type="button"
						value="Spalten hinzufügen" icon="ui-icon-triangle-1-s" />
					<p:columnToggler datasource="projectIdeas" trigger="toggler">
						<p:ajax event="toggle"
							listener="#{projectIdeaOverviewPresenter.onToggle}" />
					</p:columnToggler>
				 </h:panelGroup>
				</f:facet>
				<p:ajax event="rowSelect" update="form:projectIdeas:tblHeader"
					listener="#{projectIdeaOverviewPresenter.onRowClickSelect}" />
				

				<p:column filterBy="#{projectIdea.id}" headerText="ID"
					visible="#{projectIdeaOverviewPresenter.showColumn[0]}"
					sortBy="#{projectIdea.id}" filterMatchMode="exact">
					<h:outputText value="#{projectIdea.id}" />
				</p:column>

				<p:column filterBy="#{projectIdea.name}" headerText="Name"
					visible="#{projectIdeaOverviewPresenter.showColumn[1]}"
					sortBy="#{projectIdea.name}" filterMatchMode="contains">
					<h:outputText value="#{projectIdea.name}" />
				</p:column>

				<p:column visible="#{projectIdeaOverviewPresenter.showColumn[2]}"
					filterBy="#{projectIdea.creator.firstname} #{projectIdea.creator.lastname}"
					headerText="Ersteller"
					sortBy="#{projectIdea.creator.firstname} #{projectIdea.creator.lastname}"
					filterMatchMode="contains">
					<h:outputText
						value="#{projectIdea.creator.firstname} #{projectIdea.creator.lastname}" />
				</p:column>

				<p:column filterBy="#{projectIdea.currentSituation}" exportable="false"
					visible="#{projectIdeaOverviewPresenter.showColumn[3]}"
					headerText="Ausgangssituation"
					sortBy="#{projectIdea.currentSituation}" filterMatchMode="contains">
					<h:outputText value="#{projectIdea.currentSituation}" />
				</p:column>

				<p:column filterBy="#{projectIdea.getWorkFlowStateAsEnum(projectIdea.workflowState).name}"
					visible="#{projectIdeaOverviewPresenter.showColumn[4]}"
					headerText="Status" sortBy="projectIdea.workflowState" 
					filterMatchMode="contains">
					<h:outputText
						value="#{projectIdeaOverviewPresenter.state[projectIdea.workflowState].name}" />
				</p:column>

				<p:column filterBy="#{projectIdea.createDateAsString}" filterMatchMode="contains"
					visible="#{projectIdeaOverviewPresenter.showColumn[5]}" exportable="false"
					headerText="Erstelldatum" sortBy="#{projectIdea.createdate}">
					<h:outputText value="#{projectIdea.createdate}">
						<f:convertDateTime pattern="dd.MM.yyyy" />
					</h:outputText>
				</p:column>

				<p:column filterBy="#{projectIdea.objective}" headerText="Ziel" exportable="false"
					visible="#{projectIdeaOverviewPresenter.showColumn[6]}"
					sortBy="#{projectIdea.objective}" filterMatchMode="contains">
					<h:outputText value="#{projectIdea.objective}" />
				</p:column>

				<p:column filterBy="#{projectIdea.benefit}" headerText="Nutzen" exportable="false"
					visible="#{projectIdeaOverviewPresenter.showColumn[7]}"
					sortBy="#{projectIdea.benefit}" filterMatchMode="contains">
					<h:outputText value="#{projectIdea.benefit}" />
				</p:column>

				<p:column filterBy="#{projectIdea.department.fullname}" 
					visible="#{projectIdeaOverviewPresenter.showColumn[8]}"
					headerText="Kostenträger" sortBy="projectIdea.department.fullname"
					filterMatchMode="in">
					<f:facet name="filter">
						<p:selectCheckboxMenu label="Bitte auswählen" filter="true"
							filterMatchMode="contains"
							onchange="PF('projectIdeasTable').filter()"
							panelStyle="width:250px" scrollHeight="100">
							<f:selectItems
								value="#{projectIdeaOverviewPresenter.departments}"
								var="department" itemLabel="#{department.fullname}"
								itemValue="#{department.fullname}" />
						</p:selectCheckboxMenu>
					</f:facet>
					<h:outputText value="#{projectIdea.department.fullname}" />
				</p:column>

				<p:column filterBy="#{projectIdea.location.city}"
					visible="#{projectIdeaOverviewPresenter.showColumn[9]}"
					headerText="Standort" sortBy="projectIdea.location.city"
					filterMatchMode="in">
					<f:facet name="filter">
						<p:selectCheckboxMenu label="Bitte auswählen" filter="true"
							filterMatchMode="contains"
							onchange="PF('projectIdeasTable').filter()"
							panelStyle="width:250px" scrollHeight="100">
							<f:selectItems value="#{projectIdeaOverviewPresenter.locations}"
								var="location" itemLabel="#{location.city}"
								itemValue="#{location.city}" />
						</p:selectCheckboxMenu>
					</f:facet>
					<h:outputText value="#{projectIdea.location.city}" />
				</p:column>

				<p:column filterBy="#{projectIdea.getExtentAsEnum(projectIdea.extent)}" headerText="Ausmaß"
					visible="#{projectIdeaOverviewPresenter.showColumn[10]}" exportable="false"
					sortBy="#{projectIdea.extent}" filterMatchMode="contains">
					<h:outputText
						value="#{projectIdeaOverviewPresenter.extent[projectIdea.extent]}" />
				</p:column>

				<f:facet name="footer">
        			Insgesamt #{fn:length(projectIdeaOverviewPresenter.projectIdeas)} Projektideen eingereicht.
    			</f:facet>
			</p:dataTable>
		</h:form>
	</ui:define>

</ui:composition>