src/main/java/domain/ProjectEntity.java
package domain;

import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import config.User;
import enums.Extent;
import enums.State;
import enums.Urgency;

@Entity
@Table(name = "project")
public class ProjectEntity implements Serializable {

        private static final long serialVersionUID = -2294392989896714047L;

        public ProjectEntity() {
                // Empty Constructor for JPA
        }

        public ProjectEntity(User customer, User manager, LocationEntity location, DepartmentEntity department) {
                this.location = location;
                this.costUnit = department;
                this.customer = customer;
                this.manager = manager;
        }

        @Id
        private Integer id;

        private String name;

        @ManyToOne
        @JoinColumn(name = "customer")
        private User customer;

        @ManyToOne
        @JoinColumn(name = "manager")
        private User manager;

        @ManyToOne
        @JoinColumn(name = "location")
        private LocationEntity location;

        private Integer extent;

        private Date startdate;

        private Date enddate;

        private Integer progress;

        @Column(name = "workflow_state")
        private Integer workflowState;

        @ManyToOne
        @JoinColumn(name = "cost_unit")
        private DepartmentEntity costUnit;

        private Integer risk;

        @Column(name = "name_recognition_increase")
        private Integer nameRecognitionIncrease;

        @Column(name = "image_gain")
        private Integer imageGain;

        @Column(name = "actual_costs")
        private Integer actualCosts;

        @Column(name = "avg_proceeds_pa")
        private Integer avgProceedsPerYear;

        @Column(name = "use_duration")
        private Integer useDuration;

        @Column(name = "innovation_strategy")
        private Integer innovationStrategy;

        @Column(name = "timing_strategy")
        private Integer timingStrategy;

        @Column(name = "pricing_strategy")
        private Integer pricingStrategy;

        @Column(name = "customer_strategy")
        private Integer customerStrategy;

        private Integer urgency;

        private String objective;

        @Column(name = "current_situation")
        private String currentSituation;

        private String benefit;

        private Integer npv;

        @Column(name = "int_costs")
        private Integer intCosts;

        @Column(name = "ext_costs")
        private Integer extCosts;

        @Transient
        private Period duration;

        private Integer rating;

        private Integer roi;

        @Transient
        private Integer amortizationTime;

        // Returns amortization time in years
        public Integer getAmortizationTime() {
                if (avgProceedsPerYear != null && avgProceedsPerYear > 0) {
                        return getBudget() / avgProceedsPerYear;
                } else {
                        return 0;
                }

        }

        public Period getDuration() {
                // Convert date to LocalDate and get duration between dates
                duration = Period.between(startdate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),
                                enddate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
                return duration;
        }

        public Integer getDurationInDays() {
                // Convert date to LocalDate and get duration between dates
                duration = Period.between(startdate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),
                                enddate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
                int months = duration.getMonths();
                int years = duration.getYears();
                int days = duration.getDays();
                Integer totalDurationInDays = years * 12 * 30 + months * 30 + days;
                return totalDurationInDays;
        }

        public String getEndDateAsString() {
                String dateString = null;
                if (enddate != null) {
                        DateFormat formatter = new SimpleDateFormat("dd.MM.yyyy");
                        dateString = formatter.format(enddate);
                }
                return dateString;
        }

        public String getStartDateAsString() {
                String dateString = null;
                if (startdate != null) {
                        DateFormat formatter = new SimpleDateFormat("dd.MM.yyyy");
                        dateString = formatter.format(startdate);
                }
                return dateString;
        }

        public State getWorkFlowStateAsEnum(Integer workFlowState) {
                return State.getStateByValue(workFlowState);
        }

        public Extent getExtentAsEnum(Integer extent) {
                return Extent.getExtentByValue(extent);
        }

        public Urgency getUrgencyAsEnum(Integer urgency) {
                return Urgency.getExtentByValue(urgency);
        }

        public Integer getId() {
                return id;
        }

        public void setId(Integer id) {
                this.id = id;
        }

        public String getName() {
                return name;
        }

        public void setName(String name) {
                this.name = name;
        }

        public User getCustomer() {
                return customer;
        }

        public void setCustomer(User customer) {
                this.customer = customer;
        }

        public User getManager() {
                return manager;
        }

        public void setManager(User manager) {
                this.manager = manager;
        }

        public LocationEntity getLocation() {
                return location;
        }

        public void setLocation(LocationEntity location) {
                this.location = location;
        }

        public Integer getExtent() {
                return extent;
        }

        public void setExtent(Integer extent) {
                this.extent = extent;
        }

        public Date getStartdate() {
                return startdate;
        }

        public void setStartdate(Date startdate) {
                this.startdate = startdate;
        }

        public Date getEnddate() {
                return enddate;
        }

        public void setEnddate(Date enddate) {
                this.enddate = enddate;
        }

        public Integer getProgress() {
                return progress;
        }

        public void setProgress(Integer progress) {
                this.progress = progress;
        }

        public Integer getBudget() {
                if (intCosts != null && extCosts != null) {
                        return intCosts + extCosts;
                }
                return 0;
        }

        public Integer getWorkflowState() {
                return workflowState;
        }

        public void setWorkflowState(Integer workflowState) {
                this.workflowState = workflowState;
        }

        public DepartmentEntity getCostUnit() {
                return costUnit;
        }

        public void setCostUnit(DepartmentEntity costUnit) {
                this.costUnit = costUnit;
        }

        public Integer getRisk() {
                return risk;
        }

        public void setRisk(Integer risk) {
                this.risk = risk;
        }

        public Integer getNameRecognitionIncrease() {
                return nameRecognitionIncrease;
        }

        public void setNameRecognitionIncrease(Integer nameRecognitionIncrease) {
                this.nameRecognitionIncrease = nameRecognitionIncrease;
        }

        public Integer getImageGain() {
                return imageGain;
        }

        public void setImageGain(Integer imageGain) {
                this.imageGain = imageGain;
        }

        public Integer getActualCosts() {
                return actualCosts;
        }

        public void setActualCosts(Integer actualCosts) {
                this.actualCosts = actualCosts;
        }

        public Integer getAvgProceedsPerYear() {
                return avgProceedsPerYear;
        }

        public void setAvgProceedsPerYear(Integer avgProceedsPerYear) {
                this.avgProceedsPerYear = avgProceedsPerYear;
        }

        public Integer getUseDuration() {
                return useDuration;
        }

        public void setUseDuration(Integer useDuration) {
                this.useDuration = useDuration;
        }

        public Integer getInnovationStrategy() {
                return innovationStrategy;
        }

        public void setInnovationStrategy(Integer innovationStrategy) {
                this.innovationStrategy = innovationStrategy;
        }

        public Integer getTimingStrategy() {
                return timingStrategy;
        }

        public void setTimingStrategy(Integer timingStrategy) {
                this.timingStrategy = timingStrategy;
        }

        public Integer getPricingStrategy() {
                return pricingStrategy;
        }

        public void setPricingStrategy(Integer pricingStrategy) {
                this.pricingStrategy = pricingStrategy;
        }

        public Integer getCustomerStrategy() {
                return customerStrategy;
        }

        public void setCustomerStrategy(Integer customerStrategy) {
                this.customerStrategy = customerStrategy;
        }

        public Integer getUrgency() {
                return urgency;
        }

WebContent/secure/admin/create-project.xhtml
<ui:composition template="/template/design.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="metadata">
	</ui:define>
	<ui:define name="content">
		<h:form>
			<p:breadCrumb styleClass="ui-state-default">
				<p:menuitem value="Mein Dashboard" outcome="/secure/home.xhtml" />
				<p:menuitem value="Projekt Einreichen" outcome="create-project" />
			</p:breadCrumb>
			<div>
				<p:panel id="panel" header="Neuer Projektantrag">

					<p:messages id="msgs" />
					<p:growl id="growl" for="growl" showDetail="true" sticky="true" />

					<h:panelGrid columns="4" cellpadding="5">
						<p:outputLabel for="projectName" value="Projektantragsname:" />
						<p:inputText id="projectName" styleClass="inputFields"
							value="#{createProjectPresenter.project.name}" required="true">
							<f:validateLength minimum="5" />
						</p:inputText>

						<p:outputLabel for="projectCustomer" value="Projektauftraggeber:" />
						<p:autoComplete id="projectCustomer" minQueryLength="3"
							converter="userConverter" styleClass="inputFields"
							value="#{createProjectPresenter.project.customer}"
							completeMethod="#{createProjectPresenter.autocompleteUser}"
							var="user" itemValue="#{user}" itemLabel="#{user.fullname}"
							effect="fade" required="true" />

						<p:outputLabel for="projectManager" value="Projektleiter:" />
						<p:autoComplete id="projectManager" minQueryLength="3"
							converter="userConverter" styleClass="inputFields"
							value="#{createProjectPresenter.project.manager}" var="manager"
							itemValue="#{manager}" itemLabel="#{manager.fullname}"
							completeMethod="#{createProjectPresenter.autocompleteUser}"
							effect="fade" required="true" />

						<p:outputLabel for="location" value="Standort:" />
						<p:selectOneMenu id="location" styleClass="inputFields"
							value="#{createProjectPresenter.project.location}"
							converter="locationConverter" required="true">
							<f:selectItem itemLabel="Standort auswählen" itemValue="#{null}"
								noSelectionOption="true" />
							<f:selectItems value="#{createProjectPresenter.locations}"
								var="location" itemValue="#{location}"
								itemLabel="#{location.city}" />
						</p:selectOneMenu>

						<p:outputLabel for="projectStart" value="Projektstart:" />
						<p:calendar id="projectStart" styleClass="inputFields"
							value="#{createProjectPresenter.project.startdate}" locale="de" 
							navigator="true" pattern="dd-MM-yyyy" required="true" />

						<p:outputLabel for="projectEnd" value="Projektende:" />
						<p:calendar id="projectEnd" styleClass="inputFields"
							value="#{createProjectPresenter.project.enddate}" locale="de"
							navigator="true" pattern="dd-MM-yyyy" required="true" />

						<p:outputLabel for="projectIntCost" value="Interne Kosten:" />
						<p:inputNumber id="projectIntCost" styleClass="inputFields"
							value="#{createProjectPresenter.project.intCosts}"
							required="true" symbol=" €" symbolPosition="s" decimalPlaces="0"
							decimalSeparator="," thousandSeparator=".">
						</p:inputNumber>

						<p:outputLabel for="projectExtCost" value="Externe Kosten:" />
						<p:inputNumber id="projectExtCost" styleClass="inputFields"
							value="#{createProjectPresenter.project.extCosts}"
							decimalPlaces="0" required="true" symbol=" €" symbolPosition="s"
							decimalSeparator="," thousandSeparator=".">
						</p:inputNumber>

						<p:outputLabel for="costUnit" value="Kostenstelle:" />
						<p:selectOneMenu id="costUnit" styleClass="inputFields"
							value="#{createProjectPresenter.project.costUnit}"
							converter="departmentConverter" required="true">
							<f:selectItem itemLabel="Kostenstelle auswählen"
								itemValue="#{null}" noSelectionOption="true" />
							<f:selectItems value="#{createProjectPresenter.costUnits}"
								var="costUnit" itemValue="#{costUnit}"
								itemLabel="#{costUnit.fullname}" />
						</p:selectOneMenu>

						<p:outputLabel for="extent" value="Projektausmaß:" />
						<p:selectOneMenu id="extent" styleClass="inputFields"
							value="#{createProjectPresenter.project.extent}" required="true">
							<f:selectItem itemLabel="Projektausmaß auswählen"
								itemValue="#{null}" noSelectionOption="true" />
							<f:selectItems value="#{createProjectPresenter.extent}"
								var="extent" itemLabel="#{extent.toString()}"
								itemValue="#{extent.value}" />
						</p:selectOneMenu>

						<p:outputLabel for="projectInnovationStrat"
							value="Anpassung an die Innovationsstrategie:" />
						<p:selectOneMenu id="projectInnovationStrat"
							styleClass="inputFields"
							value="#{createProjectPresenter.project.innovationStrategy}"
							required="true">
							<f:selectItem itemLabel="Anpassung an die Innovationsstrategie"
								itemValue="#{null}" noSelectionOption="true" />
							<f:selectItems value="#{createProjectPresenter.prio}" var="prio"
								itemLabel="#{prio.name}" itemValue="#{prio.value}" />
						</p:selectOneMenu>


						<p:outputLabel for="projectTimingStrat"
							value="Anpassung an die Zeitstrategie:" />
						<p:selectOneMenu id="projectTimingStrat" styleClass="inputFields"
							value="#{createProjectPresenter.project.timingStrategy}"
							required="true">
							<f:selectItem itemLabel="Anpassung an die Zeitstrategie"
								itemValue="#{null}" noSelectionOption="true" />
							<f:selectItems value="#{createProjectPresenter.prio}" var="prio"
								itemLabel="#{prio.name}" itemValue="#{prio.value}" />
						</p:selectOneMenu>

						<p:outputLabel for="projectPricingStrat"
							value="Anpassung an die Preisstrategie:" />
						<p:selectOneMenu id="projectPricingStrat" styleClass="inputFields"
							value="#{createProjectPresenter.project.pricingStrategy}"
							required="true">
							<f:selectItem itemLabel="Anpassung an die Preisstrategie:"
								itemValue="#{null}" noSelectionOption="true" />
							<f:selectItems value="#{createProjectPresenter.prio}" var="prio"
								itemLabel="#{prio.name}" itemValue="#{prio.value}" />
						</p:selectOneMenu>


						<p:outputLabel for="projectCustomerStrat"
							value="Anpassung an die Kundenstrategie:" />
						<p:selectOneMenu id="projectCustomerStrat"
							styleClass="inputFields"
							value="#{createProjectPresenter.project.customerStrategy}"
							required="true">
							<f:selectItem itemLabel="Anpassung an die Kundenstrategie:"
								itemValue="#{null}" noSelectionOption="true" />
							<f:selectItems value="#{createProjectPresenter.prio}" var="prio"
								itemLabel="#{prio.name}" itemValue="#{prio.value}" />
						</p:selectOneMenu>


						<p:outputLabel for="projectUrgency" value="Dringlichkeit:" />
						<p:selectOneMenu id="projectUrgency" styleClass="inputFields"
							value="#{createProjectPresenter.project.urgency}" required="true">
							<f:selectItem itemLabel="Dringlichkeit:" itemValue="#{null}"
								noSelectionOption="true" />
							<f:selectItems value="#{createProjectPresenter.prio}" var="prio"
								itemLabel="#{prio.name}" itemValue="#{prio.value}" />
						</p:selectOneMenu>


						<p:outputLabel for="projectRisk" value="Projektrisiko:" />
						<p:selectOneMenu id="projectRisk" styleClass="inputFields"
							value="#{createProjectPresenter.project.risk}" required="true">
							<f:selectItem itemLabel="Projektrisiko:" itemValue="#{null}"
								noSelectionOption="true" />
							<f:selectItems value="#{createProjectPresenter.prio}" var="prio"
								itemLabel="#{prio.name}" itemValue="#{prio.value}" />
						</p:selectOneMenu>

						<p:outputLabel for="projectNameIncrease"
							value="Steigerung des Bekanntheitsgrads:" />
						<p:inputNumber id="projectNameIncrease" styleClass="inputFields"
							value="#{createProjectPresenter.project.nameRecognitionIncrease}"
							decimalPlaces="0" symbol="%" symbolPosition="s" required="true"
							emptyValue="zero" maxValue="100" minValue="0">
						</p:inputNumber>

						<p:outputLabel for="projectImgeGain" value="Imagegewinn:" />
						<p:inputNumber id="projectImgeGain" styleClass="inputFields"
							decimalPlaces="0"
							value="#{createProjectPresenter.project.imageGain}" symbol="%"
							symbolPosition="s" required="true" emptyValue="zero"
							maxValue="100" minValue="0">
						</p:inputNumber>

						<p:outputLabel for="projectAPYear"
							value="Vorraussichtlicher Erlös/Jahr:" />
						<p:inputNumber id="projectAPYear" styleClass="inputFields"
							value="#{createProjectPresenter.project.avgProceedsPerYear}"
							required="true" symbol=" €" symbolPosition="s" decimalPlaces="0"
							decimalSeparator="," thousandSeparator=".">
						</p:inputNumber>

						<p:outputLabel for="useDuration"
							value="Vorraussichtliche Nutzungsdauer:" />
						<p:inputNumber id="useDuration" styleClass="inputFields"
							value="#{createProjectPresenter.project.useDuration}"
							required="true" decimalPlaces="0" symbol=" Jahre"
							symbolPosition="s" minValue="0" maxValue="999">
						</p:inputNumber>

						<p:outputLabel for="npv" value="NPV:" />
						<p:inputNumber id="npv" styleClass="inputFields"
							value="#{createProjectPresenter.project.npv}" required="true"
							symbol=" €" symbolPosition="s" decimalSeparator=","
							decimalPlaces="0" thousandSeparator=".">
						</p:inputNumber>

						<p:outputLabel for="roi" value="ROI:" />
						<p:inputNumber id="roi" styleClass="inputFields"
							value="#{createProjectPresenter.project.roi}" required="true"
							symbol=" €" symbolPosition="s" decimalSeparator=","
							decimalPlaces="0" thousandSeparator=".">
						</p:inputNumber>

					</h:panelGrid>

					<h:panelGrid columns="2" cellpadding="5">

						<p:outputLabel for="projectCurrentSituation"
							value="Ausgangssituation:" />
						<p:inputTextarea id="projectCurrentSituation"
							value="#{createProjectPresenter.project.currentSituation}"
							required="true" rows="10" cols="100">
							<f:validateLength minimum="20" />
						</p:inputTextarea>

						<p:outputLabel for="projectObjective" value="Zielsetzung:" />
						<p:inputTextarea id="projectObjective"
							value="#{createProjectPresenter.project.objective}"
							required="true" rows="10" cols="100">
							<f:validateLength minimum="20" />
						</p:inputTextarea>

						<p:outputLabel for="projectBenefit" value="Projektnutzen:" />
						<p:inputTextarea id="projectBenefit"
							value="#{createProjectPresenter.project.benefit}" required="true"
							rows="10" cols="100">
							<f:validateLength minimum="20" />
						</p:inputTextarea>

					</h:panelGrid>
					<p:commandButton value="Projektantrag erstellen" update="panel"
						actionListener="#{createProjectPresenter.saveProject}"
						icon="ui-icon-check">
						<f:ajax onerror="window.scrollTo(0, 0);" />
					</p:commandButton>
					<p:button value="Abbrechen" outcome="/secure/home" />
				</p:panel>
			</div>
		</h:form>
	</ui:define>

</ui:composition>

WebContent/secure/admin/settings.xhtml
<ui:composition template="/template/design.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">
	<ui:define name="content">
	<p:ajaxStatus onstart="PF('statusDialog').show()" onsuccess="PF('statusDialog').hide()" />
	<p:dialog id="spinner" widgetVar="statusDialog" modal="true" draggable="false" closable="false" resizable="false" showHeader="false">
    <p:graphicImage url="/resources/images/loader.gif" /></p:dialog>
		<h:form id="settingsForm">
		<p:breadCrumb styleClass="ui-state-default">
				<p:menuitem value="Mein Dashboard" outcome="/secure/home.xhtml" />
				<p:menuitem value="Einstellungen" outcome="settings" />
			</p:breadCrumb>
			<p:tabView id="settingsTab">
				<p:ajax event="tabChange"
					listener="#{settingsPresenter.onTabChange}" />
				<p:tab id="overview" title="Übersicht">
					<p:panelGrid columns="2" style="width:50%"
						styleClass="borderless-grid">
						<h:outputText value="Timing-Strategie:" />
						<h:outputText
							value="#{settingsPresenter.currentConfiguration.timingStrategy}" />
						<h:outputText value="Preis-Strategie:" />
						<h:outputText
							value=" #{settingsPresenter.currentConfiguration.pricingStrategy}" />
						<h:outputText value="Innovations-Strategie:" />
						<h:outputText
							value=" #{settingsPresenter.currentConfiguration.innovationStrategy}" />
						<h:outputText value="Kunden-Strategie:" />
						<h:outputText
							value=" #{settingsPresenter.currentConfiguration.customerStrategy}" />
						<h:outputText value="Ammortisation:" />
						<h:outputText
							value=" #{settingsPresenter.currentConfiguration.ammortizationTime}" />
						<h:outputText value="NPV:" />
						<h:outputText
							value=" #{settingsPresenter.currentConfiguration.npv}" />
						<h:outputText value="ROI: " />
						<h:outputText
							value="#{settingsPresenter.currentConfiguration.roi}" />
						<h:outputText value="Kosten: " />
						<h:outputText
							value="#{settingsPresenter.currentConfiguration.budget}" />
						<h:outputText value="Risiko:" />
						<h:outputText
							value=" #{settingsPresenter.currentConfiguration.risk}" />
						<h:outputText value="Dauer: " />
						<h:outputText
							value="#{settingsPresenter.currentConfiguration.duration}" />
						<h:outputText value="Jahresbudget: " />
						<h:outputText
							value="#{settingsPresenter.currentConfiguration.budgetForYear}" >
							<f:convertNumber type="currency"  />
							</h:outputText>
					</p:panelGrid>
				</p:tab>
				<p:tab id="editor" title="Editieren">
					<p:growl id="growl" showDetail="true" sticky="true" />
					<h:panelGrid columns="3" columnClasses="label, value">
						<h:outputText id="timingStrat"
							value="Timing-Strategie: #{settingsPresenter.currentConfiguration.timingStrategy}" />
						<p:slider for="timingStratHidden" minValue="0" maxValue="10"
							display="timingStrat" style="width: 200px"
							displayTemplate="Timing-Strategie: {value} " />
						<h:inputHidden id="timingStratHidden"
							value="#{settingsPresenter.currentConfiguration.timingStrategy}" />

						<h:outputText id="priceStrat"
							value="Preis-Strategie: #{settingsPresenter.currentConfiguration.pricingStrategy}" />
						<p:slider for="priceStratHidden" minValue="0" maxValue="10"
							display="priceStrat" style="width: 200px"
							displayTemplate="Preis-Strategie: {value} " />
						<h:inputHidden id="priceStratHidden"
							value="#{settingsPresenter.currentConfiguration.pricingStrategy}" />

						<h:outputText id="customerStrat"
							value="Kunden-Strategie: #{settingsPresenter.currentConfiguration.customerStrategy}" />
						<p:slider for="customerStratHidden" minValue="0" maxValue="10"
							display="customerStrat" style="width: 200px"
							displayTemplate="Kunden-Strategie: {value} " />
						<h:inputHidden id="customerStratHidden"
							value="#{settingsPresenter.currentConfiguration.customerStrategy}" />

						<h:outputText id="innovationStrat"
							value="Innovations-Strategie: #{settingsPresenter.currentConfiguration.innovationStrategy}" />
						<p:slider for="innovationStratHidden" minValue="0" maxValue="10"
							display="innovationStrat" style="width: 200px"
							displayTemplate="Innovations-Strategie: {value} " />
						<h:inputHidden id="innovationStratHidden"
							value="#{settingsPresenter.currentConfiguration.innovationStrategy}" />

						<h:outputText id="budget"
							value="Kosten: #{settingsPresenter.currentConfiguration.budget}" />
						<p:slider for="budgetHidden" minValue="0" maxValue="10"
							display="budget" style="width: 200px"
							displayTemplate="Kosten: {value} " />
						<h:inputHidden id="budgetHidden"
							value="#{settingsPresenter.currentConfiguration.budget}" />

						<h:outputText id="npv"
							value="NPV: #{settingsPresenter.currentConfiguration.npv}" />
						<p:slider for="npvHidden" minValue="0" maxValue="10" display="npv"
							style="width: 200px" displayTemplate="NPV: {value} " />
						<h:inputHidden id="npvHidden"
							value="#{settingsPresenter.currentConfiguration.npv}" />

						<h:outputText id="ammortization"
							value="Ammortisation: #{settingsPresenter.currentConfiguration.ammortizationTime}" />
						<p:slider for="ammortizationHidden" minValue="0" maxValue="10"
							display="ammortization" style="width: 200px"
							displayTemplate="Ammortisation: {value} " />
						<h:inputHidden id="ammortizationHidden"
							value="#{settingsPresenter.currentConfiguration.ammortizationTime}" />

						<h:outputText id="roi"
							value="ROI: #{settingsPresenter.currentConfiguration.roi}" />
						<p:slider for="roiHidden" minValue="0" maxValue="10" display="roi"
							style="width: 200px" displayTemplate="ROI: {value} " />
						<h:inputHidden id="roiHidden"
							value="#{settingsPresenter.currentConfiguration.roi}" />

						<h:outputText id="risk"
							value="Risiko: #{settingsPresenter.currentConfiguration.risk}" />
						<p:slider for="riskHidden" minValue="0" maxValue="10"
							display="risk" style="width: 200px"
							displayTemplate="Risiko: {value} " />
						<h:inputHidden id="riskHidden"
							value="#{settingsPresenter.currentConfiguration.risk}" />

						<h:outputText id="duration"
							value="Dauer: #{settingsPresenter.currentConfiguration.duration}" />
						<p:slider for="durationHidden" minValue="0" maxValue="10"
							display="duration" style="width: 200px"
							displayTemplate="Dauer: {value} " />
						<h:inputHidden id="durationHidden"
							value="#{settingsPresenter.currentConfiguration.duration}" />
						<h:outputText id="budgetForAYear" value="Jahresbudget:" />
						<p:inputNumber id="budgetForAYearInput" 
							value="#{settingsPresenter.currentConfiguration.budgetForYear}"
							required="true" symbol=" €" symbolPosition="s" decimalPlaces="0"
							decimalSeparator="," thousandSeparator="."/><div></div>
						<p:commandButton value="Speichern"
							actionListener="#{settingsPresenter.saveConfiguration}"
							update="growl" />
						<p:button value="Abbrechen" outcome="/secure/home" />
					</h:panelGrid>
				</p:tab>
			</p:tabView>
		</h:form>
	</ui:define>
</ui:composition>